baseURL = 'https://blog.rfaychen.com/'
languageCode = 'en'
DefaultContentLanguage = "zh-tw"
title = "足跡"
theme = "hulga"
paginate = 10

[params]
  # show in HTML meta tag
  author = "陳智育"
  description = "試圖在網路上留下一些足跡"

  # change bulma's primary color
  primaryColor = "#1793d0"

  # copyright text on footer
  copyright = "Copyright © 2022 wlh. All rights reserved."

  # enable katex rendering on every post page
  math = true

  # enable postcss, mainly for css purge (129kB->20kB->4.8kB gzipped, but this makes build slower)
  postcss = true

  # enable toc on every post page
  toc = true

  # enable TOC auto collapse
  autoCollapseToc = true

  # enable prefers-color-scheme:dark
  darkMedia = true

  # enable hero section's is-bold effect
  heroBold = true

  # enable PWA, prepare your icons and DON'T forget to modify manifest.json
  pwa = true

  # disable jsdelivr cdn, default false
  noCDN = false

# to enable different hightlight themes in light/dark mode 
[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "archives"
    name = "Archive"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "@智育"
    url = "/about/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"

googleAnalytics = "G-H6V37Y5E7Z"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5